### ISSUE TITLE
Sync failed: please check your network connection.

### ISSUE THREAD

**Issue by CatTail** [hackjutsu/Lepton#46]
I use Version 1.0.0-beta.3 (1.0.0-beta.3), and **CAN** connect to Github gist, but this message keep coming, DevTool console told me

```
Unhandled rejection TypeError: Cannot convert undefined or null to object
    at NavigationPanel.renderLangTags (file:///Applications/Lepton.app/Contents/Resources/app.asar/bundle/app.bundle.js:1962:14)
    at NavigationPanel.renderTagSection (file:///Applications/Lepton.app/Contents/Resources/app.asar/bundle/app.bundle.js:2019:16)
    at NavigationPanel.render (file:///Applications/Lepton.app/Contents/Resources/app.asar/bundle/app.bundle.js:2052:14)
    at /Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
    at measureLifeCyclePerf (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at Object.updateChildren (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:121:51)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:208:32)
    at ReactDOMComponent._updateChildren (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:936:12)
    at ReactDOMComponent.updateComponent (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:754:10)
    at ReactDOMComponent.receiveComponent (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:716:10)
    at Object.receiveComponent (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:125:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:754:23)
```

**Comment by aaronice** [comment]
Same issue with Version 1.0.0-beta.3 on Mac OS X.

![image](https://cloud.githubusercontent.com/assets/3983543/22612235/366cede6-ea24-11e6-812c-60d08f0a3d35.png)

The issue occurs during login, and Lepton hangs in the loading phase.

![image](https://cloud.githubusercontent.com/assets/3983543/22612272/78346862-ea24-11e6-83f4-3bdfbab7e09f.png)

**Comment by hackjutsu** [comment]
@aaronice Can you paste the log in `~/Library/Application Support/Lepton/logs`?

**Comment by CatTail** [comment]
@hackjutsu log result are

```
2017-02-03T23:04:05.834Z - info: Found user profile null
2017-02-03T23:04:07.370Z - info: [Dispatch] updateAuthWindowStatus ON
2017-02-03T23:04:32.228Z - info: [Dispatch] updateAuthWindowStatus OFF
2017-02-03T23:04:32.232Z - info: [Dispatch] updateUserSession IN_PROGRESS
2017-02-03T23:04:34.307Z - info: [Dispatch] updateUserSession IN_PROGRESS
2017-02-03T23:04:34.309Z - info: [Dispatch] updateAccessToken
2017-02-03T23:04:38.087Z - debug: The gist number on this page is 30
2017-02-03T23:04:40.033Z - debug: The gist number on this page is 30
2017-02-03T23:04:41.778Z - debug: The gist number on this page is 30
2017-02-03T23:04:42.862Z - debug: The gist number on this page is 3
2017-02-03T23:04:44.013Z - debug: The gist number on this page is 0
2017-02-03T23:04:44.022Z - error: The request has failed: TypeError: Cannot read property 'match' of null
2017-02-03T23:04:44.023Z - info: [Dispatch] updateUserSession ACTIVE
2017-02-03T23:04:59.345Z - info: Found user profile null
2017-02-03T23:05:00.771Z - info: [Dispatch] updateAuthWindowStatus ON
2017-02-03T23:05:25.349Z - info: [Dispatch] updateAuthWindowStatus OFF
2017-02-03T23:05:25.355Z - info: [Dispatch] updateUserSession IN_PROGRESS
2017-02-03T23:05:27.031Z - info: [Dispatch] updateUserSession IN_PROGRESS
2017-02-03T23:05:27.034Z - info: [Dispatch] updateAccessToken
2017-02-03T23:05:30.536Z - debug: The gist number on this page is 30
2017-02-03T23:05:32.357Z - debug: The gist number on this page is 30
2017-02-03T23:05:34.396Z - debug: The gist number on this page is 30
2017-02-03T23:05:35.626Z - debug: The gist number on this page is 3
2017-02-03T23:05:36.889Z - debug: The gist number on this page is 0
2017-02-03T23:05:36.901Z - error: The request has failed: TypeError: Cannot read property 'match' of null
2017-02-03T23:05:36.902Z - info: [Dispatch] updateUserSession ACTIVE
2017-02-04T00:53:13.418Z - info: The app window is closed
```

**Comment by hackjutsu** [comment]
@CatTail Got it. This is caused by a `null` value when parsing the description.

```javascript
export function descriptionParser (rawDescription = 'AWESOME GIST') {
  const regexForTitle = rawDescription.match(/\[.*\]/)
  const rawTitle = regexForTitle && regexForTitle[0] || ''
  const title = (rawTitle.length > 0) && rawTitle.substring(1, regexForTitle[0].length - 1) || ''

  const regextForCustomTags = rawDescription.match(/#tags:.*$/)
  const customTags = regextForCustomTags && regextForCustomTags[0] || ''

  const description = rawDescription.substring(rawTitle.length, rawDescription.length - customTags.length)

  return { title, description, customTags }
}
```

I thought the es6 initial value in the argument list will handle the case when the arg is `null`. But it turns out it only works when there is no args or the arg is `undefined`. 
> Default function parameters allow formal parameters to be initialized with default values if no value or undefined is passed. [ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)

Good lesson learned. I'll fix it soon

**Comment by hackjutsu** [comment]
Should be fixed:https://github.com/hackjutsu/Lepton/commit/6af171eaea98915f2a0ec268468f5c817179086a

**Comment by ustrugany** [comment]
Issue still is happening to me on version 1.5.0 on macos, unable to login and use app.

**Comment by hansjons** [comment]
Hi I'm on 1.5.0 on macos 10.13.2 and am getting the "Sync failed message". The dev console does not show any message at all. Lepton was working ok until I added some gists with a `[title]` and tags `#` then I was logged out and am now getting the sync message. I tried changing the gists directly on github but Lepton is still in a limbo.

**Comment by hackjutsu** [comment]
@hansjons Try delete `~/Library/Application Support/Lepton/` in v1.5.0, or try the alpha release for 1.5.1.
https://github.com/hackjutsu/Lepton/releases/tag/v1.5.1-alpha

**Comment by hansjons** [comment]
@hackjutsu I tried both and can confirm that both methods worked for me. Cool app by the way and thanks for the prompt reply:-)

**Comment by TimeBandit** [comment]
I'm seeing this issue on Ubuntu 18.04.1 LTS on my desktop. 
Still work on 16.0.4 LTS on my laptop. 
The upgrade to the latest LTS version of Ubuntu on my desktop somehow broke Lepton

**Comment by vamsden** [comment]
Can confirm same issue still persist in Ubuntu 18.04 LTS

**Comment by TimeBandit** [comment]
A dedicated issue was raised here.
